/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ContactsIndexRouteImport } from './routes/contacts/index'
import { Route as ContactsContactIdRouteImport } from './routes/contacts/$contactId'
import { Route as LeadsIndexRouteImport } from './routes/leads/index'
import { Route as LeadsLeadIdRouteImport } from './routes/leads/$leadId'
import { Route as PlatformIndexRouteImport } from './routes/platform/index'
import { Route as PlatformLoginRouteImport } from './routes/platform/login'
import { Route as PropertiesIndexRouteImport } from './routes/properties/index'
import { Route as PropertiesPropertyIdRouteImport } from './routes/properties/$propertyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsIndexRoute = ContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsContactIdRoute = ContactsContactIdRouteImport.update({
  id: '/contacts/$contactId',
  path: '/contacts/$contactId',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIndexRoute = LeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsLeadIdRoute = LeadsLeadIdRouteImport.update({
  id: '/leads/$leadId',
  path: '/leads/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/platform/',
  path: '/platform/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformLoginRoute = PlatformLoginRouteImport.update({
  id: '/platform/login',
  path: '/platform/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesPropertyIdRoute = PropertiesPropertyIdRouteImport.update({
  id: '/properties/$propertyId',
  path: '/properties/$propertyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/admin': typeof AdminRoute
  '/assistant': typeof AssistantRoute
  '/automation': typeof AutomationRoute
  '/calendar': typeof CalendarRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/platform/login': typeof PlatformLoginRoute
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/contacts/': typeof ContactsIndexRoute
  '/leads/': typeof LeadsIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/properties/': typeof PropertiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/admin': typeof AdminRoute
  '/assistant': typeof AssistantRoute
  '/automation': typeof AutomationRoute
  '/calendar': typeof CalendarRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/platform/login': typeof PlatformLoginRoute
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/contacts': typeof ContactsIndexRoute
  '/leads': typeof LeadsIndexRoute
  '/platform': typeof PlatformIndexRoute
  '/properties': typeof PropertiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/admin': typeof AdminRoute
  '/assistant': typeof AssistantRoute
  '/automation': typeof AutomationRoute
  '/calendar': typeof CalendarRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/platform/login': typeof PlatformLoginRoute
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/contacts/': typeof ContactsIndexRoute
  '/leads/': typeof LeadsIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/properties/': typeof PropertiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate'
    | '/admin'
    | '/assistant'
    | '/automation'
    | '/calendar'
    | '/inbox'
    | '/login'
    | '/notifications'
    | '/offers'
    | '/reports'
    | '/settings'
    | '/contacts/$contactId'
    | '/leads/$leadId'
    | '/platform/login'
    | '/properties/$propertyId'
    | '/contacts/'
    | '/leads/'
    | '/platform/'
    | '/properties/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activate'
    | '/admin'
    | '/assistant'
    | '/automation'
    | '/calendar'
    | '/inbox'
    | '/login'
    | '/notifications'
    | '/offers'
    | '/reports'
    | '/settings'
    | '/contacts/$contactId'
    | '/leads/$leadId'
    | '/platform/login'
    | '/properties/$propertyId'
    | '/contacts'
    | '/leads'
    | '/platform'
    | '/properties'
  id:
    | '__root__'
    | '/'
    | '/activate'
    | '/admin'
    | '/assistant'
    | '/automation'
    | '/calendar'
    | '/inbox'
    | '/login'
    | '/notifications'
    | '/offers'
    | '/reports'
    | '/settings'
    | '/contacts/$contactId'
    | '/leads/$leadId'
    | '/platform/login'
    | '/properties/$propertyId'
    | '/contacts/'
    | '/leads/'
    | '/platform/'
    | '/properties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivateRoute: typeof ActivateRoute
  AdminRoute: typeof AdminRoute
  AssistantRoute: typeof AssistantRoute
  AutomationRoute: typeof AutomationRoute
  CalendarRoute: typeof CalendarRoute
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  OffersRoute: typeof OffersRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  ContactsContactIdRoute: typeof ContactsContactIdRoute
  LeadsLeadIdRoute: typeof LeadsLeadIdRoute
  PlatformLoginRoute: typeof PlatformLoginRoute
  PropertiesPropertyIdRoute: typeof PropertiesPropertyIdRoute
  ContactsIndexRoute: typeof ContactsIndexRoute
  LeadsIndexRoute: typeof LeadsIndexRoute
  PlatformIndexRoute: typeof PlatformIndexRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/': {
      id: '/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof ContactsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/$contactId': {
      id: '/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof ContactsContactIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/': {
      id: '/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof LeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/$leadId': {
      id: '/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof LeadsLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/': {
      id: '/platform/'
      path: '/platform'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/login': {
      id: '/platform/login'
      path: '/platform/login'
      fullPath: '/platform/login'
      preLoaderRoute: typeof PlatformLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$propertyId': {
      id: '/properties/$propertyId'
      path: '/properties/$propertyId'
      fullPath: '/properties/$propertyId'
      preLoaderRoute: typeof PropertiesPropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivateRoute: ActivateRoute,
  AdminRoute: AdminRoute,
  AssistantRoute: AssistantRoute,
  AutomationRoute: AutomationRoute,
  CalendarRoute: CalendarRoute,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  OffersRoute: OffersRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  ContactsContactIdRoute: ContactsContactIdRoute,
  LeadsLeadIdRoute: LeadsLeadIdRoute,
  PlatformLoginRoute: PlatformLoginRoute,
  PropertiesPropertyIdRoute: PropertiesPropertyIdRoute,
  ContactsIndexRoute: ContactsIndexRoute,
  LeadsIndexRoute: LeadsIndexRoute,
  PlatformIndexRoute: PlatformIndexRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
